<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <Authors>cmoski, BobLd</Authors>
    <Version>0.0.3</Version>
    <PackageId>Camelot.Sharp.Cmoski</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>A C# library to extract tabular data from PDFs (port of camelot Python version using PdfPig). Maintained fork with fixes for multi-column text splitting.</Description>
    <PackageTags>pdf, extract, table, camelot, pdfpig, parse, extraction, export</PackageTags>
    <RepositoryUrl>https://github.com/cmoski/camelot-sharp</RepositoryUrl>
    <PackageProjectUrl>https://github.com/cmoski/camelot-sharp</PackageProjectUrl>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReleaseNotes>Fixed Lattice parser text splitting for multi-column tables</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.11" />
  </ItemGroup>
</Project>